
services:
  mysqldb:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=some_password
      - MYSQL_DATABASE=demodb
      - MYSQL_ROOT_HOST=%
    container_name: "mysqldb"
    networks:
      - my-network
    healthcheck:
      test: ['CMD','mysqladmin','ping','-h','localhost']
      timeout: 20s
      retries: 10

  mypythonapp:
    build: ./
    container_name: mypyapp
    networks:
      - my-network
    volumes:
      - ./server.txt:/myapp/server.txt
    depends_on:
      mysqldb:
        condition: service_healthy
    stdin_open: true
    tty: true
       
networks:
  my-network:
